#!/usr/bin/env node

var args = process.argv;

args = args.slice(typeof __ejs !== 'undefined' ? 1 : 2);

var toolname = 'pirouette';

var project = require('./util/project'),
    usage = require('./commands/global/usage');


function getCommands() {
    var proj = project.Project.findContaining ();
    if (proj) {
	try {
	    return require('./commands/'+proj.config.projectType+'/commands').commands;
	}
	catch (e) {
	    console.log(e);
	}
    }
    return require('./commands/global/commands').commands;
}

var commands = getCommands();
usage.installCommands(commands);


if (args.length === 0) {
    usage.printUsage();
    process.exit(0);
}

var cmd = commands[args[0]];

if (cmd) {
    cmd.run (args.slice(1), function() {
	// something needs to happen here..
    });
}
else {
    console.log(toolname + ": Unknown command `" + args[0] + "'");
}

// Local Variables:
// mode: javascript
// End:

