#!/usr/bin/env node

var args = process.argv;

// slice off the right number of arguments
args = args.slice(typeof __ejs !== 'undefined' ? 1 : 2);

var toolname = "pirouette";

var createCommand = require("./commands/create"),
    buildCommand  = require("./commands/build"),
    simCommand    = require("./commands/sim"),
    devCommand    = require("./commands/dev"),
    cleanCommand  = require("./commands/clean"),
    compileCommand  = require("./commands/compile");


var commands = Object.create (null, {
    help: { enumerable: true, value: {
	usage: function(s) { return s + " <Command>"; },
	usageString: function(s) { return ": gives more detailed help for <Command>, or this output if no command is given."; },
	run: function(args) {
	    if (args.length === 0) {
		return usage();
	    }
	    throw "help command not implemented";
	}
    }},

    create: { enumerable: true, value: {
	usage: function(s) { return s + " <ProjectType> <ProjectName>"; },
	usageString: function(nl_and_indent) {
	    return              ": generates initial project template named <ProjectName> in current directory." +
		nl_and_indent("    where <ProjectType> is <target_platform>/<template_name>") +
		nl_and_indent("        currently only these are supported:") +
		nl_and_indent("          osx/application") +
		nl_and_indent("          ios/application");
	},

	run: function(args) {
	    createCommand.run(args, function() {
	    });
	}
    }},

    build: { enumerable: true, value: {
	usage: function(s) { return s; },
	usageString: function(s) { return ": Builds the current project."; },
	run: function(args) {
	    buildCommand.run(args, function() {
	    });
	}
    }},

    clean: { enumerable: true, value: {
	usage: function(s) { return s; },
	usageString: function(s) { return ": Cleans the current project."; },
	run: function(args) {
	    cleanCommand.run(args, function() {
	    });
	}
    }},

    sim: { enumerable: true, value: {
	usage: function(s) { return s; },
	usageString: function(s) { return ": deploy the current project to the simulator (only available for ios projects)."; },
	run: function(args) {
	    // the default build behavior is to build if necessary
	    buildCommand.run([], function() {
		simCommand.run(args, function() {
		});
	    });
	}
    }},

    dev: { enumerable: true, value: {
	usage: function(s) { return s; },
	usageString: function(s) { return ": deploy the current project to the device (only available for ios projects)."; },
	run: function(args) {
	    // the default build behavior is to build if necessary
	    buildCommand.run([], function() {
		devCommand.run(args, function() {
		});
	    });
	}
    }},

    compile: { enumerable: true, value: {
	usage: function(s) { return s; },
	usageString: function(s) { return ": deploy the current project to the device (only available for ios projects)."; },
	run: function(args) {
	    compileCommand.run(args, function() {
	    });
	}
    }}
});
	    

function usage() {
    var justify_col = 40;

    function justify(str) {
	var justify_str = new Array(50).join(" ");
	return str + justify_str.substring(0, justify_col - str.length);
    }

    console.log (" $ " + toolname + " [options] <command>");
    console.log ("where <command> is one of the following:");
    for (var cmdname in commands) {
	var cmd = commands[cmdname];
	console.log ("  " + justify(cmd.usage(cmdname)) + cmd.usageString(function(str) { return "\n" + justify("") + str; }));
    }
}

if (args.length === 0) {
    usage();
    process.exit(0);
}

var cmd = commands[args[0]];

if (cmd) {
    cmd.run (args.slice(1));
/*
    try {
	cmd.run (args.slice(1));
    }
    catch (e) {
	console.log (toolname + ": command `" + args[0] + "' failed:");
	console.log (e);
    }
*/
}
else {
    console.log(toolname + ": Unknown command `" + args[0] + "'");
}

// Local Variables:
// mode: javascript
// End:

